name: EDGAR IPO Watch

on:
  schedule:
    # Runs every 20 minutes (UTC)
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests feedparser

      - name: Test Discord webhook
        if: github.event_name == 'workflow_dispatch'
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            --data '{"content":"🔔 [Test] EDGAR IPO Notifier is up and running!"}' \
            ${{ secrets.DISCORD_WEBHOOK }}

      - name: Run EDGAR IPO notifier
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          USER_AGENT:       "SEC WATCHER"
          STATE_FILE:       "seen_entries.json"
        run: |
          python EDGAR.py
